### ISSUE TITLE
Using set method

### ISSUE THREAD

**Issue by wdecoster** [pimoroni/piglow#13]
Great starting material. Although relatively simple, the piglow is making me very enthusiast and it's a nice first experience with addons on the Pi.

The readme suggests the following command: set(0, 255) - sets LED 0 to full brightness
Perhaps this is implied since the sentence above states 'The set method ...' but I guess many people will first find out that set(0, 255) is not what they expect (makes sense) and instead piglow.set(0, 255) should be used. I would suggest to clarify this.

**Comment by Gadgetoid** [comment]
Good point. I've updated the readme to reflect this!
