### ISSUE TITLE
Installation with pip issue

### ISSUE THREAD

**Issue by 1030ahmad1030** [pimoroni/piglow#19]
I had these errors while trying to install using pip install

"" ERROR: Command errored out with exit status 1:""

**Comment by Gadgetoid** [comment]
Any idea what version of pip/python you're using? You can find this with `pip --version` or `pip3 --version`.

Is there any other information preceeding this error? There should be some lines describing exactly what went wrong. A screenshot or copy & paste of the command output will help.

**Comment by 1030ahmad1030** [comment]
By the way, I installed the pyglow and it's not running properly. now let
me tell you the following if you have any python package installed in your
computer (I am using ANACONDA
https://www.anaconda.com/distribution/  ):-
(1) press your windows button and begin to type cmd in your search panel.
(2) you are expected to see two or more suggestions, one for windows and
the other for python. else you need to download and install python command
prompt.
(3)  if you see it, then select and click on the python cmd and click.
(4)and that is where you paste the code I sent you and run.
(5) the code will enable you computer access Github and make downloads or
cloning.
(6) and finally, you follow the pyglow instructions to install and use in
your computer.
please tell me if pyglow runs successfully in your own end.

**Comment by Gadgetoid** [comment]
This GitHub repository is for `piglow`, your issue seems to be with `pyglow`. I'm afraid I can't help with that.
