### ISSUE TITLE
pip won't install piglow

### ISSUE THREAD

**Issue by clickwir** [pimoroni/piglow#3]
pi@raspberrypi ~/piglow $ sudo pip install piglow
Downloading/unpacking piglow
  Could not find a version that satisfies the requirement piglow (from versions: 1.1dev, 1.2dev)
Cleaning up...
No distributions matching the version for piglow
Storing debug log for failure in /root/.pip/pip.log

pi@raspberrypi ~/piglow $ sudo cat /root/.pip/pip.log
/usr/bin/pip run on Fri Jul 24 01:44:44 2015
Downloading/unpacking piglow
  Getting page https://pypi.python.org/simple/piglow/
  URLs to search for versions for piglow:
   https://pypi.python.org/simple/piglow/
  Analyzing links from page https://pypi.python.org/simple/piglow/
    Found link https://pypi.python.org/packages/source/p/piglow/piglow-1.1dev.tar.gz#md5=cb9e06c76fd623f9f2d48809773cf458 (from https://pypi.python.org/simple/piglow/), version: 1.1dev
    Found link https://pypi.python.org/packages/source/p/piglow/piglow-1.2dev.tar.gz#md5=42ea0e3ae95a2af341d72c38857b1baa (from https://pypi.python.org/simple/piglow/), version: 1.2dev
  Ignoring link https://pypi.python.org/packages/source/p/piglow/piglow-1.1dev.tar.gz#md5=cb9e06c76fd623f9f2d48809773cf458 (from https://pypi.python.org/simple/piglow/), version 1.1dev is a pre-release (use --pre to allow).
  Ignoring link https://pypi.python.org/packages/source/p/piglow/piglow-1.2dev.tar.gz#md5=42ea0e3ae95a2af341d72c38857b1baa (from https://pypi.python.org/simple/piglow/), version 1.2dev is a pre-release (use --pre to allow).
  Could not find a version that satisfies the requirement piglow (from versions: 1.1dev, 1.2dev)
Cleaning up...
No distributions matching the version for piglow
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 290, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1178, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 322, in find_requirement
    raise DistributionNotFound('No distributions matching the version for %s' % req)
DistributionNotFound: No distributions matching the version for piglow

pi@raspberrypi ~/piglow $ pip --version
pip 1.5.6 from /usr/lib/python2.7/dist-packages (python 2.7)

I don't know if this might be related: https://stackoverflow.com/a/18319230

**Comment by Gadgetoid** [comment]
This was an issue with installing pre-release packages via pip, it should have been fixed in: a3378222b039b9b332a5bb806875adb881dc965f
