### ISSUE TITLE
Installer error

### ISSUE THREAD

**Issue by lurch** [pimoroni/piglow#9]
When running the `curl get.pimoroni.com/piglow | bash` command as instructed, it says
```
sh: line 274: dt_check: command not found
```

But it then carries on as normal, so I guess it's not quite a fatal error?

**Comment by Gadgetoid** [comment]
I can't see a reference to `dt_check` in the installer script, so perhaps this has been fixed since? https://github.com/pimoroni/get/blob/master/installers/piglow

Probably best to open an issue against the get repo if not!

Cheers.

**Comment by lurch** [comment]
Yeah, fixed in https://github.com/pimoroni/get/commit/404522371d942f510eabf35885d8d332b4f8db98
(ironically just 3 days after I opened this issue!)
